//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMG_ITC
{


    public partial class SOCPanel
    {

        /// <summary>
        /// summaryCards control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl summaryCards;

        /// <summary>
        /// lblTotal control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTotal;

        /// <summary>
        /// lblOpen control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblOpen;

        /// <summary>
        /// lblResolved control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblResolved;

        /// <summary>
        /// lblClosed control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblClosed;

        /// <summary>
        /// tabQueue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton tabQueue;

        /// <summary>
        /// tabResolved control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton tabResolved;

        /// <summary>
        /// tabAll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton tabAll;

        /// <summary>
        /// badgeQueue control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeQueue;

        /// <summary>
        /// badgeResolved control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeResolved;

        /// <summary>
        /// pnlQueue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlQueue;

        /// <summary>
        /// panelQueueEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel panelQueueEmpty;

        /// <summary>
        /// gvQueue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvQueue;

        /// <summary>
        /// pnlResolved control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResolved;

        /// <summary>
        /// panelResolvedEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel panelResolvedEmpty;

        /// <summary>
        /// gvResolved control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvResolved;

        /// <summary>
        /// pnlAll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAll;

        /// <summary>
        /// ddlStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>
        /// ddlPriority control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlPriority;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// btnClear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;

        /// <summary>
        /// btnRefresh control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnRefresh;

        /// <summary>
        /// gvAll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvAll;

        /// <summary>
        /// assignComplaintId control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl assignComplaintId;

        /// <summary>
        /// ddlEngineer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEngineer;

        /// <summary>
        /// txtAssignNote control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAssignNote;

        /// <summary>
        /// btnConfirmAssign control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmAssign;

        /// <summary>
        /// closeComplaintId control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl closeComplaintId;

        /// <summary>
        /// txtCloseReason control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCloseReason;

        /// <summary>
        /// btnConfirmClose control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmClose;

        /// <summary>
        /// hfActionComplaintId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfActionComplaintId;
    }
}
