//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintPage
{
    public partial class WebForm1
    {
        protected global::System.Web.UI.WebControls.TextBox txtSubject;

        protected global::System.Web.UI.WebControls.DropDownList ddlPriority;

        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        protected global::System.Web.UI.WebControls.DropDownList ddlUnit;

        protected global::System.Web.UI.WebControls.TextBox txtRequestCenterCode;

        protected global::System.Web.UI.WebControls.TextBox txtRequestCenterDesc;

        protected global::System.Web.UI.WebControls.TextBox txtRequestTypeCode;

        protected global::System.Web.UI.WebControls.TextBox txtRequestTypeDesc;

        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        protected global::System.Web.UI.WebControls.FileUpload fileInput;

        protected global::System.Web.UI.WebControls.DropDownList ddlCustomerImpact;

        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
